# Generated by Django 5.0.4 on 2024-04-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(default='Kathmandu', max_length=100),
        ),
    ]
