# Generated by Django 5.0.4 on 2024-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
